import SidebarComponent from "@/components/SidebarComponent";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import { Provider } from "@/context/provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <Provider>{children}</Provider>
        
      </body>
    </html>
  );
}
